// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SecondaryFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDI99ZuHHUEY2WESdaUp-wviUGwo4AwY',
    appId: '1:491305267684:web:10e565916fdff317ec17f1',
    messagingSenderId: '491305267684',
    projectId: 'senzehch',
    authDomain: 'senzehch.firebaseapp.com',
    databaseURL: 'https://senzehch-default-rtdb.firebaseio.com',
    storageBucket: 'senzehch.appspot.com',
    measurementId: 'G-NHNV5FGVGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFq4GNcoTfbIt3TbVLL48WQEUX3MhpXM',
    appId: '1:491305267684:android:0df5069a3a5faf72ec17f1',
    messagingSenderId: '491305267684',
    projectId: 'senzehch',
    databaseURL: 'https://senzehch-default-rtdb.firebaseio.com',
    storageBucket: 'senzehch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_jjfSyUQN8KM5Hr2G7vwJSeR2eLbJc8',
    appId: '1:491305267684:ios:ff34f118b41313a1ec17f1',
    messagingSenderId: '491305267684',
    projectId: 'senzehch',
    databaseURL: 'https://senzehch-default-rtdb.firebaseio.com',
    storageBucket: 'senzehch.appspot.com',
    androidClientId: '491305267684-ad4jet02fchc0h25ntt1aeck01raark7.apps.googleusercontent.com',
    iosClientId: '491305267684-ug7vc8k2fj9979gpm1m8bdu6up495qub.apps.googleusercontent.com',
    iosBundleId: 'com.senzehub.senzepact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_jjfSyUQN8KM5Hr2G7vwJSeR2eLbJc8',
    appId: '1:491305267684:ios:ff34f118b41313a1ec17f1',
    messagingSenderId: '491305267684',
    projectId: 'senzehch',
    databaseURL: 'https://senzehch-default-rtdb.firebaseio.com',
    storageBucket: 'senzehch.appspot.com',
    iosClientId: '491305267684-ug7vc8k2fj9979gpm1m8bdu6up495qub.apps.googleusercontent.com',
    iosBundleId: 'com.senzehub.senzepact',
  );

}
